apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource-monitoring-app.name" . }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resource-monitoring-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "resource-monitoring-app.name" . }}
      
    spec:
      containers:
        - name: {{ include "resource-monitoring-app.name" . }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}