apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-monitoring-app.name" . }}-service
spec:
  selector:
    app: {{ include "resource-monitoring-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-monitoring-app.fullname" . }}-lb-service
spec:
  selector:
    app: {{ include "resource-monitoring-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containerPort }}
  type: LoadBalancer
