name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chucthien-app:latest

    - name: Install and update AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Configure AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "${{ secrets.AWS_TOKEN }}" > ~/.aws/credentials
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 271718395217.dkr.ecr.us-east-1.amazonaws.com
        docker tag chucthien-app:latest 271718395217.dkr.ecr.us-east-1.amazonaws.com/chucthien-app:latest
        docker push 271718395217.dkr.ecr.us-east-1.amazonaws.com/chucthien-app:latest
